-- NOTE:
-- This migration is intentionally a no-op.
--
-- The sensor intel tables were created in the earlier migration:
--   20260204120000_add_fleet_intel_snapshots
--
-- Keeping this migration (but empty) avoids Prisma trying to create the same tables
-- twice during `prisma migrate reset/deploy`.
