{{- if and .Values.enabled .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "synapse-fleet.fullname" . }}
  labels:
    {{- include "synapse-fleet.labels" . | nindent 4 }}
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- toYaml .Values.global.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "synapse-fleet.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    - {}
{{- end }}
