{{- if and .Values.enabled .Values.podDisruptionBudget.enabled (or (gt (int .Values.replicaCount) 1) (and .Values.autoscaling.enabled (gt (int .Values.autoscaling.minReplicas) 1))) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "synapse-fleet.fullname" . }}
  labels:
    {{- include "synapse-fleet.labels" . | nindent 4 }}
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- toYaml .Values.global.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "synapse-fleet.selectorLabels" . | nindent 6 }}
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
{{- end }}
