{{- if and .Values.enabled .Values.migrations.enabled .Values.migrations.hook.enabled .Values.database.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synapse-fleet.migrationsSecretName" . }}
  labels:
    {{- include "synapse-fleet.labels" . | nindent 4 }}
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations (and .Values.migrations.enabled .Values.migrations.hook.enabled) }}
  annotations:
    {{- with .Values.global.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if and .Values.migrations.enabled .Values.migrations.hook.enabled }}
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-15"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    {{- end }}
  {{- end }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
{{- end }}
