{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "synapse-fleet.fullname" . }}
  labels:
    {{- include "synapse-fleet.labels" . | nindent 4 }}
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.service.annotations }}
  annotations:
    {{- with .Values.global.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "synapse-fleet.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
{{- end }}
