/**
 * Sigma Rule Background Hunting
 *
 * Idea 5: run persisted Sigma-derived queries against ClickHouse on a schedule,
 * generating "hunting leads" for the SOC to review.
 *
 * NOTE: We intentionally do NOT accept arbitrary SQL from clients. We accept a
 * Sigma UI-generated query template and extract/validate the WHERE clause.
 */

import crypto from 'crypto';
import type { Logger } from 'pino';
import type { ClickHouseService } from '../../storage/clickhouse/index.js';
import type { RedisKv } from '../../storage/redis/kv.js';
import { buildRedisKey } from '../../storage/redis/keys.js';
import { jsonDecode, jsonEncode } from '../../storage/redis/json.js';

export class SigmaValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'SigmaValidationError';
  }
}

export type SigmaRule = {
  id: string;
  tenantId: string;
  name: string;
  description?: string;
  enabled: boolean;
  /** Original SQL template generated by the Sigma UI (for transparency / debugging). */
  sqlTemplate: string;
  /** Validated WHERE clause extracted from sqlTemplate. */
  whereClause: string;
  createdAt: string;
  updatedAt: string;
};

export type SigmaLeadStatus = 'OPEN' | 'ACKED';

export type SigmaLead = {
  id: string;
  tenantId: string;
  ruleId: string;
  ruleName: string;
  status: SigmaLeadStatus;
  acknowledgedAt: string | null;
  firstSeenAt: string;
  lastSeenAt: string;
  matchCount: number;
  pivot: {
    requestId: string | null;
    anonFingerprint: string | null;
    sourceIp: string | null;
  };
  sample: {
    timestamp: string;
    sensorId: string;
    signalType: string;
    severity: string;
    confidence: number;
  };
};

export type CreateSigmaRuleInput = {
  name: string;
  description?: string;
  sqlTemplate: string;
  enabled?: boolean;
};

export type UpdateSigmaRuleInput = {
  name?: string;
  description?: string;
  enabled?: boolean;
};

const NAMESPACE = 'sigma-hunt';
const VERSION = 1;

function tenantsKey(): string {
  return buildRedisKey({
    namespace: NAMESPACE,
    version: VERSION,
    tenantId: 'global',
    dataType: 'tenants',
    id: 'all',
  });
}

function ruleIdsKey(tenantId: string): string {
  return buildRedisKey({
    namespace: NAMESPACE,
    version: VERSION,
    tenantId,
    dataType: 'rule-ids',
    id: 'all',
  });
}

function ruleKey(tenantId: string, ruleId: string): string {
  return buildRedisKey({
    namespace: NAMESPACE,
    version: VERSION,
    tenantId,
    dataType: 'rule',
    id: ruleId,
  });
}

function ruleCursorKey(tenantId: string, ruleId: string): string {
  return buildRedisKey({
    namespace: NAMESPACE,
    version: VERSION,
    tenantId,
    dataType: 'rule-cursor',
    id: ruleId,
  });
}

function leadIdsKey(tenantId: string): string {
  return buildRedisKey({
    namespace: NAMESPACE,
    version: VERSION,
    tenantId,
    dataType: 'lead-ids',
    id: 'all',
  });
}

function leadKey(tenantId: string, leadId: string): string {
  return buildRedisKey({
    namespace: NAMESPACE,
    version: VERSION,
    tenantId,
    dataType: 'lead',
    id: leadId,
  });
}

function stableLeadId(input: string): string {
  return crypto.createHash('sha256').update(input).digest('hex').slice(0, 24);
}

function stripLeadingComments(sql: string): string {
  const lines = sql.split('\n');
  let i = 0;
  for (; i < lines.length; i += 1) {
    const line = lines[i] ?? '';
    if (line.trim().startsWith('--')) continue;
    if (line.trim() === '') continue;
    break;
  }
  return lines.slice(i).join('\n').trim();
}

function stripSingleQuotedLiterals(sql: string): string {
  // Replace ClickHouse single-quoted strings, respecting escaped ''.
  return sql.replace(/'(?:''|[^'])*'/g, "''");
}

function hasBalancedSingleQuotes(sql: string): boolean {
  // ClickHouse escapes a single quote inside a string as ''.
  //
  // NOTE: This intentionally does NOT implement backslash-escape semantics (e.g. `\'`).
  // We defensively reject obvious injection via downstream forbidden-fragment checks after
  // stripping single-quoted literals, and we treat unbalanced quotes as invalid input.
  let inQuote = false;
  for (let i = 0; i < sql.length; i += 1) {
    const ch = sql[i]!;
    if (ch !== "'") continue;

    if (!inQuote) {
      inQuote = true;
      continue;
    }

    const next = sql[i + 1];
    if (next === "'") {
      // Escaped quote inside a string literal.
      i += 1;
      continue;
    }

    inQuote = false;
  }
  return !inQuote;
}

function hasDangerousControlChars(sql: string): boolean {
  // Reject ASCII control characters that can cause parser ambiguity.
  // Allow tab/newline/carriage return as they normalize via whitespace collapsing.
  return /[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/.test(sql);
}

export function extractAndValidateSigmaWhereClause(sqlTemplate: string): string {
  const trimmed = stripLeadingComments(sqlTemplate);
  if (trimmed.length === 0) throw new SigmaValidationError('Sigma SQL template is empty');
  if (trimmed.length > 50_000) throw new SigmaValidationError('Sigma SQL template too large');

  const match = trimmed.match(
    /^select\s+\*\s+from\s+signal_events\s+where\s+([\s\S]+?)\s+order\s+by\s+timestamp\s+desc\s+limit\s+\d+\s*$/i
  );
  if (!match) {
    throw new SigmaValidationError(
      'Sigma SQL template must match: SELECT * FROM signal_events WHERE ... ORDER BY timestamp DESC LIMIT N'
    );
  }

  const whereClause = (match[1] ?? '').trim();
  if (!whereClause) throw new SigmaValidationError('Sigma SQL template WHERE clause is empty');
  if (whereClause.length > 20_000) throw new SigmaValidationError('Sigma WHERE clause too large');
  if (!hasBalancedSingleQuotes(whereClause)) {
    throw new SigmaValidationError('Sigma WHERE clause contains unbalanced single quotes');
  }
  if (hasDangerousControlChars(whereClause)) {
    throw new SigmaValidationError('Sigma WHERE clause contains forbidden control characters');
  }

  // Reject obvious injection vectors outside string literals.
  // Normalize whitespace so tabs/newlines can't bypass fragment checks.
  //
  // NOTE: We must validate balanced quotes *before* stripping literals. The literal-stripping regex
  // only understands ClickHouse `''` escaping and would become unsafe if used on unbalanced input.
  const stripped = stripSingleQuotedLiterals(whereClause).replace(/\s+/g, ' ').toLowerCase();

  const forbiddenFragments = [
    ';',
    '--',
    '/*',
    '*/',
  ];

  const forbiddenKeywords: Array<{ label: string; re: RegExp }> = [
    { label: 'format', re: /\bformat\b/ },
    { label: 'into outfile', re: /\binto\s+outfile\b/ },
    { label: 'select', re: /\bselect\b/ },
    { label: 'insert', re: /\binsert\b/ },
    { label: 'update', re: /\bupdate\b/ },
    { label: 'delete', re: /\bdelete\b/ },
    { label: 'drop', re: /\bdrop\b/ },
    { label: 'alter', re: /\balter\b/ },
    { label: 'create', re: /\bcreate\b/ },
    { label: 'attach', re: /\battach\b/ },
    { label: 'detach', re: /\bdetach\b/ },
    { label: 'system', re: /\bsystem\b/ },
    // ClickHouse statement-level keywords we never expect in a Sigma WHERE clause.
    { label: 'explain', re: /\bexplain\b/ },
    { label: 'show', re: /\bshow\b/ },
    { label: 'set', re: /\bset\b/ },
    { label: 'describe', re: /\bdescribe\b/ },
    { label: 'truncate', re: /\btruncate\b/ },
    { label: 'rename', re: /\brename\b/ },
    { label: 'grant', re: /\bgrant\b/ },
    { label: 'revoke', re: /\brevoke\b/ },
    { label: 'kill', re: /\bkill\b/ },
    { label: 'optimize', re: /\boptimize\b/ },
    { label: 'exchange', re: /\bexchange\b/ },
    { label: 'union', re: /\bunion\b/ },
  ];

  // ClickHouse table functions / external data sources (SSRF/exfiltration risk).
  // Use regex so whitespace like `remote (` can't bypass checks.
  const forbiddenCalls: Array<{ label: string; re: RegExp }> = [
    { label: 'remote(', re: /\bremote\s*\(/ },
    { label: 'remotesecure(', re: /\bremotesecure\s*\(/ },
    { label: 'cluster(', re: /\bcluster\s*\(/ },
    { label: 'clusterallreplicas(', re: /\bclusterallreplicas\s*\(/ },
    { label: 'url(', re: /\burl\s*\(/ },
    { label: 'file(', re: /\bfile\s*\(/ },
    { label: 's3(', re: /\bs3\s*\(/ },
    { label: 'hdfs(', re: /\bhdfs\s*\(/ },
    { label: 'jdbc(', re: /\bjdbc\s*\(/ },
    { label: 'mysql(', re: /\bmysql\s*\(/ },
    { label: 'postgresql(', re: /\bpostgresql\s*\(/ },
    { label: 'input(', re: /\binput\s*\(/ },
    { label: 'odbc(', re: /\bodbc\s*\(/ },
    { label: 'dictionary(', re: /\bdictionary\s*\(/ },
    { label: 'merge(', re: /\bmerge\s*\(/ },
  ];

  for (const frag of forbiddenFragments) {
    if (stripped.includes(frag)) {
      throw new SigmaValidationError(`Sigma WHERE clause contains forbidden fragment: ${frag.trim()}`);
    }
  }
  for (const k of forbiddenKeywords) {
    if (k.re.test(stripped)) {
      throw new SigmaValidationError(`Sigma WHERE clause contains forbidden fragment: ${k.label}`);
    }
  }
  for (const call of forbiddenCalls) {
    if (call.re.test(stripped)) {
      throw new SigmaValidationError(`Sigma WHERE clause contains forbidden fragment: ${call.label}`);
    }
  }

  // Basic sanity: must reference only known table columns and safe functions.
  // We keep this loose to avoid breaking legitimate Sigma rules, but disallow backticks.
  if (stripped.includes('`')) throw new SigmaValidationError('Sigma WHERE clause contains forbidden character: `');
  // Double quotes can be used for identifiers in ClickHouse; we disallow to reduce bypass surface.
  if (stripped.includes('"')) throw new SigmaValidationError('Sigma WHERE clause contains forbidden character: "');

  return whereClause;
}

type ClickHouseSigmaRow = {
  timestamp: string;
  sensor_id: string;
  request_id: string | null;
  signal_type: string;
  source_ip: string;
  anon_fingerprint: string;
  severity: string;
  confidence: number;
};

export class SigmaHuntService {
  constructor(
    private readonly kv: RedisKv,
    private readonly logger: Logger,
    private readonly clickhouse: ClickHouseService | null
  ) {}

  async createRule(tenantId: string, input: CreateSigmaRuleInput): Promise<SigmaRule> {
    if (!tenantId) throw new SigmaValidationError('tenantId is required');
    if (!input.name || input.name.length > 120) throw new SigmaValidationError('name is required (max 120 chars)');
    if (input.description && input.description.length > 2000) {
      throw new SigmaValidationError('description too long (max 2000 chars)');
    }

    const whereClause = extractAndValidateSigmaWhereClause(input.sqlTemplate);
    const now = new Date().toISOString();
    const rule: SigmaRule = {
      id: crypto.randomUUID(),
      tenantId,
      name: input.name,
      description: input.description,
      enabled: input.enabled ?? true,
      sqlTemplate: input.sqlTemplate,
      whereClause,
      createdAt: now,
      updatedAt: now,
    };

    await this.kv.set(ruleKey(tenantId, rule.id), jsonEncode(rule));
    await this.kv.sadd(ruleIdsKey(tenantId), rule.id);
    await this.kv.sadd(tenantsKey(), tenantId);

    this.logger.info({ tenantId, ruleId: rule.id }, 'Sigma rule created');
    return rule;
  }

  async listRules(tenantId: string): Promise<SigmaRule[]> {
    const ids = await this.kv.smembers(ruleIdsKey(tenantId));
    if (ids.length === 0) return [];

    const raws = await this.kv.mget(ids.map((id) => ruleKey(tenantId, id)));
    const rules: SigmaRule[] = [];
    const missingIds: string[] = [];

    for (let i = 0; i < ids.length; i += 1) {
      const id = ids[i]!;
      const raw = raws[i];
      if (!raw) {
        missingIds.push(id);
        continue;
      }
      const parsed = jsonDecode<SigmaRule>(raw, { maxBytes: 200_000 });
      // Defensive: enforce tenant match.
      if (parsed.tenantId !== tenantId) continue;
      rules.push(parsed);
    }

    if (missingIds.length > 0) {
      await this.kv.srem(ruleIdsKey(tenantId), ...missingIds);
    }

    rules.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
    return rules;
  }

  async updateRule(tenantId: string, ruleId: string, input: UpdateSigmaRuleInput): Promise<SigmaRule | null> {
    const raw = await this.kv.get(ruleKey(tenantId, ruleId));
    if (!raw) return null;
    const existing = jsonDecode<SigmaRule>(raw, { maxBytes: 200_000 });
    if (existing.tenantId !== tenantId) return null;

    if (input.name !== undefined) {
      if (!input.name || input.name.length > 120) throw new SigmaValidationError('name is required (max 120 chars)');
    }
    if (input.description !== undefined) {
      if (input.description && input.description.length > 2000) {
        throw new SigmaValidationError('description too long (max 2000 chars)');
      }
    }

    // Explicitly pick properties to avoid accidental mass-assignment if stored data is ever corrupted.
    const next: SigmaRule = {
      id: existing.id,
      tenantId: existing.tenantId,
      name: input.name ?? existing.name,
      description: input.description ?? existing.description,
      enabled: input.enabled ?? existing.enabled,
      sqlTemplate: existing.sqlTemplate,
      whereClause: existing.whereClause,
      createdAt: existing.createdAt,
      updatedAt: new Date().toISOString(),
    };

    await this.kv.set(ruleKey(tenantId, ruleId), jsonEncode(next));
    return next;
  }

  async deleteRule(tenantId: string, ruleId: string): Promise<boolean> {
    const raw = await this.kv.get(ruleKey(tenantId, ruleId));
    if (!raw) return false;
    const existing = jsonDecode<SigmaRule>(raw, { maxBytes: 200_000 });
    if (existing.tenantId !== tenantId) return false;

    await this.kv.del(ruleKey(tenantId, ruleId));
    await this.kv.del(ruleCursorKey(tenantId, ruleId));
    await this.kv.srem(ruleIdsKey(tenantId), ruleId);
    return true;
  }

  async listLeads(tenantId: string, limit: number = 200): Promise<SigmaLead[]> {
    const ids = await this.kv.smembers(leadIdsKey(tenantId));
    if (ids.length === 0) return [];

    const raws = await this.kv.mget(ids.map((id) => leadKey(tenantId, id)));
    const leads: SigmaLead[] = [];
    const missingIds: string[] = [];
    for (let i = 0; i < ids.length; i += 1) {
      const id = ids[i]!;
      const raw = raws[i];
      if (!raw) {
        missingIds.push(id);
        continue;
      }
      const parsed = jsonDecode<SigmaLead>(raw, { maxBytes: 200_000 });
      if (parsed.tenantId !== tenantId) continue;
      leads.push(parsed);
    }

    if (missingIds.length > 0) {
      await this.kv.srem(leadIdsKey(tenantId), ...missingIds);
    }

    leads.sort((a, b) => b.lastSeenAt.localeCompare(a.lastSeenAt));
    return leads.slice(0, Math.max(1, Math.min(1000, limit)));
  }

  async ackLead(tenantId: string, leadId: string): Promise<SigmaLead | null> {
    const raw = await this.kv.get(leadKey(tenantId, leadId));
    if (!raw) return null;
    const existing = jsonDecode<SigmaLead>(raw, { maxBytes: 200_000 });
    if (existing.tenantId !== tenantId) return null;

    const next: SigmaLead = {
      ...existing,
      status: 'ACKED',
      acknowledgedAt: existing.acknowledgedAt ?? new Date().toISOString(),
    };

    await this.kv.set(leadKey(tenantId, leadId), jsonEncode(next), { ttlSeconds: 7 * 24 * 60 * 60 });
    return next;
  }

  /**
   * Run all enabled rules for all tenants with rules (global set), incrementally.
   * Safe for multi-instance: scheduling is coordinated by BullMQ; worker concurrency is 1.
   */
  async runScheduledHunts(options?: {
    lookbackMinutes?: number;
    maxRowsPerRule?: number;
  }): Promise<{ tenants: number; rules: number; matches: number; leadsUpserted: number }> {
    const lookbackMinutes = Math.max(5, Math.min(24 * 60, options?.lookbackMinutes ?? 60));
    const maxRowsPerRule = Math.max(10, Math.min(5000, options?.maxRowsPerRule ?? 500));

    if (!this.clickhouse?.isEnabled()) {
      this.logger.warn('ClickHouse disabled; sigma background hunts skipped');
      return { tenants: 0, rules: 0, matches: 0, leadsUpserted: 0 };
    }

    const tenantIds = await this.kv.smembers(tenantsKey());
    let rulesCount = 0;
    let matches = 0;
    let leadsUpserted = 0;

    const now = new Date();
    const endTime = now.toISOString().replace('T', ' ').replace('Z', '');
    const defaultStart = new Date(now.getTime() - lookbackMinutes * 60 * 1000);

    for (const tenantId of tenantIds) {
      const rules = await this.listRules(tenantId);
      const enabledRules = rules.filter((r) => r.enabled);
      for (const rule of enabledRules) {
        rulesCount += 1;

        const cursorRaw = await this.kv.get(ruleCursorKey(tenantId, rule.id));
        const cursor = cursorRaw ? new Date(cursorRaw) : defaultStart;
        // Overlap by 5 minutes to avoid missing late-arriving rows.
        const start = new Date(Math.min(cursor.getTime(), now.getTime()) - 5 * 60 * 1000);
        const startTime = start.toISOString().replace('T', ' ').replace('Z', '');

        const rows = await this.queryMatches(tenantId, rule.whereClause, startTime, endTime, maxRowsPerRule);
        matches += rows.length;
        for (const row of rows) {
          const leadId = this.computeLeadId(rule.id, row);
          const upserted = await this.upsertLead(tenantId, leadId, rule, row);
          if (upserted) leadsUpserted += 1;
        }

        await this.kv.set(ruleCursorKey(tenantId, rule.id), now.toISOString());
      }
    }

    return { tenants: tenantIds.length, rules: rulesCount, matches, leadsUpserted };
  }

  private computeLeadId(ruleId: string, row: ClickHouseSigmaRow): string {
    const requestId = row.request_id ?? '';
    const anonFp = row.anon_fingerprint && !/^0+$/.test(row.anon_fingerprint) ? row.anon_fingerprint : '';
    const sourceIp = row.source_ip ?? '';
    const basis = requestId || anonFp || `${sourceIp}:${row.signal_type}`;
    return stableLeadId(`${ruleId}:${basis}`);
  }

  private async queryMatches(
    tenantId: string,
    whereClause: string,
    startTime: string,
    endTime: string,
    limit: number
  ): Promise<ClickHouseSigmaRow[]> {
    const sql = `
      SELECT
        timestamp,
        sensor_id,
        request_id,
        signal_type,
        IPv4NumToString(source_ip) AS source_ip,
        anon_fingerprint,
        severity,
        confidence
      FROM signal_events
      WHERE tenant_id = {tenantId:String}
        AND timestamp >= toDateTime64({startTime:String}, 3)
        AND timestamp <= toDateTime64({endTime:String}, 3)
        AND (${whereClause})
      ORDER BY timestamp DESC
      LIMIT {limit:UInt32}
    `;

    return this.clickhouse!.queryWithParams<ClickHouseSigmaRow>(sql, { tenantId, startTime, endTime, limit });
  }

  private async upsertLead(
    tenantId: string,
    leadId: string,
    rule: SigmaRule,
    row: ClickHouseSigmaRow
  ): Promise<boolean> {
    const key = leadKey(tenantId, leadId);
    const raw = await this.kv.get(key);
    const ts = new Date(row.timestamp).toISOString();

    if (!raw) {
      const lead: SigmaLead = {
        id: leadId,
        tenantId,
        ruleId: rule.id,
        ruleName: rule.name,
        status: 'OPEN',
        acknowledgedAt: null,
        firstSeenAt: ts,
        lastSeenAt: ts,
        matchCount: 1,
        pivot: {
          requestId: row.request_id ?? null,
          anonFingerprint: row.anon_fingerprint && !/^0+$/.test(row.anon_fingerprint) ? row.anon_fingerprint : null,
          sourceIp: row.source_ip || null,
        },
        sample: {
          timestamp: ts,
          sensorId: row.sensor_id,
          signalType: row.signal_type,
          severity: row.severity,
          confidence: row.confidence,
        },
      };

      await this.kv.set(key, jsonEncode(lead), { ttlSeconds: 7 * 24 * 60 * 60 });
      await this.kv.sadd(leadIdsKey(tenantId), leadId);
      return true;
    }

    const existing = jsonDecode<SigmaLead>(raw, { maxBytes: 200_000 });
    const next: SigmaLead = {
      ...existing,
      ruleName: rule.name, // in case rule renamed
      lastSeenAt: ts > existing.lastSeenAt ? ts : existing.lastSeenAt,
      firstSeenAt: ts < existing.firstSeenAt ? ts : existing.firstSeenAt,
      matchCount: existing.matchCount + 1,
      // If previously acked, keep ack but reopen on new activity.
      status: existing.status === 'ACKED' ? 'OPEN' : existing.status,
      acknowledgedAt: existing.status === 'ACKED' ? null : existing.acknowledgedAt,
      sample: {
        timestamp: ts,
        sensorId: row.sensor_id,
        signalType: row.signal_type,
        severity: row.severity,
        confidence: row.confidence,
      },
    };

    await this.kv.set(key, jsonEncode(next), { ttlSeconds: 7 * 24 * 60 * 60 });
    return false;
  }
}
